export const TRUSTED_GOVERNMENT_DOMAINS = [
  "indonesia.go.id",
  "lapor.go.id",
  "data.go.id",
  "domain.go.id",

  "presidenri.go.id",
  "setneg.go.id",

  "polkam.go.id",
  "ekon.go.id",
  "kemenkopmk.go.id",
  "maritim.go.id",

  "kemendagri.go.id",
  "kemlu.go.id",
  "kemenkeu.go.id",
  "kemenkum.go.id",
  "kemenag.go.id",
  "kemdikbud.go.id",
  "kemendikdasmen.go.id",
  "kemdiktisaintek.go.id",
  "kemenkes.go.id",
  "kemensos.go.id",
  "kemenkop.go.id",
  "kemenperin.go.id",
  "kemendag.go.id",
  "kementan.go.id",
  "kementrans.go.id",
  "kemendikdasmen.go.id",
  "kemdiktisaintek.go.id",
  "kemenbud.go.id",
  "kemenpar.go.id",
  "ekraf.go.id",
  "esdm.go.id",
  "pu.go.id",
  "komdigi.go.id",
  "kemenparekraf.go.id",
  "kemenpora.go.id",
  "kemenpppa.go.id",
  "kemenpan.go.id",

"kemhan.go.id",
"kemenham.go.id",
"kemenimipas.go.id",
"kemenhut.go.id",
"menlh.go.id",
"kkp.go.id",
"kemenhub.go.id",
"kemnaker.go.id",
"kemendes.go.id",
"kemendespdt.go.id",
"kemenbud.go.id",
"kemenpar.go.id",
"kemenparekraf.go.id",
"kemenekraf.go.id",
"kemenumkm.go.id",
"pkp.go.id",
"kemenp2mi.go.id",
"kemendukbangga.go.id",
"bkkbn.go.id",

// ===== LEMBAGA NEGARA =====
"bi.go.id",
"ojk.go.id",
"lkpp.go.id",
"bps.go.id",
"bsn.go.id",
"brin.go.id",
"bakamla.go.id",
"basarnas.go.id",
"bakn.go.id",
"bakosurtanal.go.id",
"big.go.id",
"bmkg.go.id",
"bapeten.go.id",
"batan.go.id",
"bphn.go.id",
"bpom.go.id",
"bakamla.go.id",
"bppt.go.id",
"lan.go.id",
"lemhannas.go.id",
"perpusnas.go.id",
"anri.go.id",
"bpsdm.go.id",

// ===== BADAN / LEMBAGA =====
"bpjs-kesehatan.go.id",
"bpjskesehatan.go.id",
"bpjsketenagakerjaan.go.id",
"baznas.go.id",
"bwi.go.id",
"kpk.go.id",
"ppatk.go.id",
"lps.go.id",
"lpsk.go.id",
"kpai.go.id",
"kpi.go.id",
"kip.go.id",
"bphmigas.go.id",
"bphn.go.id",
"bpkh.go.id",
"bsip.go.id",
"bskdn.go.id",
"bsn.go.id",

// ===== DIREKTORAT JENDERAL KEMENKEU =====
"djp.go.id",
"pknstan.ac.id",
"beacukai.go.id",
"djbc.go.id",
"djkn.go.id",
"djpb.go.id",
"dja.go.id",
"djppr.kemenkeu.go.id",
"djpbn.kemenkeu.go.id",
"spanint.kemenkeu.go.id",

// ===== DJP ONLINE =====
"ereg.pajak.go.id",
"efiling.pajak.go.id",
"efaktur.pajak.go.id",
"djponline.pajak.go.id",
"pajak.go.id",

// ===== BKN =====
"asnkarier.bkn.go.id",
"helpdesk-sscasn.bkn.go.id",
"cat.bkn.go.id",

// ===== KEMKES =====
"ayosehat.kemkes.go.id",
"yankes.kemkes.go.id",
"kemkes.go.id",
"farmalkes.kemkes.go.id",
"promkes.kemkes.go.id",

// ===== KEMENDIKDASMEN / PENDIDIKAN =====
"pusmendik.kemdikbud.go.id",
"pusdatin.kemdikbud.go.id",
"kampusmerdeka.kemdikbud.go.id",
"dikdasmen.go.id",
"vokasi.kemdikbud.go.id",
"gtk.kemdikbud.go.id",

// ===== ATR/BPN =====
"bhumi.atrbpn.go.id",
"sentuh.tanahku.go.id",

// ===== IMIGRASI =====
"evisa.imigrasi.go.id",
"molina.imigrasi.go.id",
"visa-online.imigrasi.go.id",

// ===== KPU =====
"pemilu2024.kpu.go.id",
"jdih.kpu.go.id",

// ===== POLRI =====
"ditlantas.polri.go.id",
"propam.polri.go.id",
"divhumas.polri.go.id",

// ===== KEJAKSAAN =====
"tilang.kejaksaan.go.id",
"e-tilang.kejaksaan.go.id",

// ===== MAHKAMAH AGUNG =====
"badilag.mahkamahagung.go.id",
"badilum.mahkamahagung.go.id",
"badiltun.mahkamahagung.go.id",
"kepaniteraan.mahkamahagung.go.id",

// ===== LAYANAN NASIONAL =====
"jdihn.go.id",
"jdih.setneg.go.id",
"sp4n.lapor.go.id",
"srikandi.go.id",
"ina.digital",
"portal-snpmb.bppp.kemdikbud.go.id",
"pdn.go.id",
"sso.go.id",
"peruri.co.id",
"lpdp.kemenkeu.go.id",
"jdih.setkab.go.id",
"setkab.go.id",
"jdih.bpk.go.id",
"jdih.dpr.go.id",
"jdihn.go.id",
"direktori.info.go.id",
"ppid.go.id",
"cekrekening.id",
"cekrekening.ojk.go.id",
  "bappenas.go.id",
  "atrbpn.go.id",
  "bkpm.go.id",

  "dpr.go.id",
  "dpd.go.id",
  "mpr.go.id",
  "bpk.go.id",
  "mahkamahagung.go.id",
  "mkri.id",
  "ky.go.id",

  "bnn.go.id",
  "bnpb.go.id",
  "bpip.go.id",
  "bssn.go.id",
  "bpkp.go.id",
  "bkn.go.id",
  "bawaslu.go.id",
  "kpu.go.id",
  "ombudsman.go.id",
  "bea-cukai.go.id",
  "pajak.go.id",
  "imigrasi.go.id",
  "kejaksaan.go.id",
  "polri.go.id",

  "cekbansos.kemensos.go.id",
  "sscasn.bkn.go.id",
  "djponline.pajak.go.id",
  "oss.go.id",
  "satu-sehat.go.id",
  "satusehat.kemkes.go.id",
  "lpse.go.id",

  // ================================
// PORTAL PEMERINTAH NASIONAL
// ================================
"indonesia.go.id",
"lapor.go.id",
"sp4n.lapor.go.id",
"oss.go.id",
"jdihn.go.id",
"data.go.id",
"satu.data.go.id",
"portal-satu.data.go.id",
"ppid.go.id",
"lpse.go.id",
"srikandi.go.id",
"ina.digital",
"cekrekening.id",
"peruri.co.id",
"domain.go.id",
"satudata.go.id",
"simbara.esdm.go.id",
"e-katalog.lkpp.go.id",
"inaproc.id",
"sipd.kemendagri.go.id",
"jdih.setneg.go.id",
"jdih.setkab.go.id",
"setkab.go.id",
"jdih.dpr.go.id",
"jdih.bpk.go.id",
"jdih.mahkamahagung.go.id",
"jdih.kemenkeu.go.id",
"jdih.kemenkum.go.id",
"ppid.kemenkeu.go.id",
"ppid.kemkes.go.id",
"ppid.kemdikbud.go.id",
"ppid.bkn.go.id",

"djp.go.id",
"pajak.go.id",
"djponline.pajak.go.id",
"ereg.pajak.go.id",
"efiling.pajak.go.id",
"efaktur.pajak.go.id",
"djp.pajak.go.id",
"kringpajak.go.id",
"pajak2.go.id",
"pajakonline.go.id",
"inspektorat.pajak.go.id",
"klc2.kemenkeu.go.id",

"djbc.go.id",
"beacukai.go.id",
"bea-cukai.go.id",
"eservice.insw.go.id",
"insw.go.id",
"portal.insw.go.id",
"ceisa.beacukai.go.id",
"ceisa40.beacukai.go.id",
"eska.beacukai.go.id",
"klikbc.beacukai.go.id",
"learning.beacukai.go.id",
"klc.beacukai.go.id",

"djkn.kemenkeu.go.id",
"lelang.go.id",
"portal.lelang.go.id",
"lelangdjkn.kemenkeu.go.id",
"e-auction.djkn.kemenkeu.go.id",
"siman.kemenkeu.go.id",
"kn.kemenkeu.go.id",

"dja.kemenkeu.go.id",
"anggaran.kemenkeu.go.id",
"monev.kemenkeu.go.id",
"smartdja.kemenkeu.go.id",
"sakti.kemenkeu.go.id",
"span.kemenkeu.go.id",

"djpb.kemenkeu.go.id",
"omspan.kemenkeu.go.id",
"sakti.kemenkeu.go.id",
"spanint.kemenkeu.go.id",
"span.kemenkeu.go.id",
"silabi.kemenkeu.go.id",
"hai.djpb.kemenkeu.go.id",
"e-rekon.kemenkeu.go.id",
"digit.kemenkeu.go.id",
"simaspaten.kemenkeu.go.id",
"ejafung.kemenkeu.go.id",

"bkn.go.id",
"sscasn.bkn.go.id",
"helpdesk-sscasn.bkn.go.id",
"asnkarier.bkn.go.id",
"cat.bkn.go.id",
"siasn.bkn.go.id",
"myasn.bkn.go.id",
"e-kinerja.bkn.go.id",
"monitoring-siasn.bkn.go.id",
"diklat.bkn.go.id",
"simpeg.bkn.go.id",
"karier.bkn.go.id",

"kemkes.go.id",
"satusehat.kemkes.go.id",
"satu-sehat.go.id",
"ayosehat.kemkes.go.id",
"yankes.kemkes.go.id",
"farmalkes.kemkes.go.id",
"promkes.kemkes.go.id",
"alkes.kemkes.go.id",
"regalkes.kemkes.go.id",
"sehatnegeriku.kemkes.go.id",
"pusdatin.kemkes.go.id",
"infeksiemerging.kemkes.go.id",
"kesmas.kemkes.go.id",
"gizi.kemkes.go.id",
"sdmk.kemkes.go.id",
"rsonline.kemkes.go.id",

"kemendikdasmen.go.id",
"spmb.kemendikdasmen.go.id",
"spasikita.kemendikdasmen.go.id",
"gtk.kemdikbud.go.id",
"guru.kemdikbud.go.id",
"pusmendik.kemdikbud.go.id",
"pusdatin.kemdikbud.go.id",
"vokasi.kemdikbud.go.id",
"dapo.kemdikbud.go.id",
"dapodik.kemdikbud.go.id",
"vervalpd.data.kemdikbud.go.id",
"vervalptk.data.kemdikbud.go.id",
"ijazah.kemdikbud.go.id",
"referensi.data.kemdikbud.go.id",
"bos.kemdikbud.go.id",
"rumahbelajar.kemdikbud.go.id",

"kemdiktisaintek.go.id",
"bima.kemdiktisaintek.go.id",
"sinta.kemdiktisaintek.go.id",
"pddikti.kemdiktisaintek.go.id",
"garuda.kemdiktisaintek.go.id",
"silemkerma.kemdiktisaintek.go.id",
"kedaireka.kemdiktisaintek.go.id",
"kampusmerdeka.kemdikbud.go.id",
"sister.kemdikbud.go.id",
"arjuna.kemdikbud.go.id",
"simlitabmas.kemdikbud.go.id",


// KPU

"kpu.go.id",
"infopemilu.kpu.go.id",
"pemilu2024.kpu.go.id",
"jdih.kpu.go.id",
"ppid.kpu.go.id",
"cekdptonline.kpu.go.id",
"sidalih.kpu.go.id",
"silon.kpu.go.id",
"sirekap.kpu.go.id",
"sipol.kpu.go.id",
"sidapil.kpu.go.id",
"sidakam.kpu.go.id",
"situng.kpu.go.id",
"simpeg.kpu.go.id",
"lpse.kpu.go.id",
"eppid.kpu.go.id",


// MAHKAMAH AGUNG

"mahkamahagung.go.id",
"kepaniteraan.mahkamahagung.go.id",
"badilag.mahkamahagung.go.id",
"badilum.mahkamahagung.go.id",
"badiltun.mahkamahagung.go.id",
"badilmiltun.mahkamahagung.go.id",
"bawas.mahkamahagung.go.id",
"balitbangdiklatkumdil.mahkamahagung.go.id",
"sipp.mahkamahagung.go.id",
"ecourt.mahkamahagung.go.id",
"eraterang.mahkamahagung.go.id",
"eberpadu.mahkamahagung.go.id",
"e-bima.mahkamahagung.go.id",
"sikep.mahkamahagung.go.id",
"simari.mahkamahagung.go.id",
"siper.mahkamahagung.go.id",
"eprima.mahkamahagung.go.id",
"sakip.mahkamahagung.go.id",
"eiplans.mahkamahagung.go.id",
"pnbp.mahkamahagung.go.id",
"komdanas.mahkamahagung.go.id",
"llk.mahkamahagung.go.id",
"perpustakaan.mahkamahagung.go.id",
"ppid.mahkamahagung.go.id",
"jdih.mahkamahagung.go.id",

// =========================
// POLRI
// =========================
"polri.go.id",
"presisi.polri.go.id",
"skck.polri.go.id",
"sim.polri.go.id",
"etle-pmj.id",
"etle-korlantas.info",
"korlantas.polri.go.id",
"ditlantas.polri.go.id",
"propam.polri.go.id",
"divhumas.polri.go.id",
"intelkam.polri.go.id",
"wasidik.polri.go.id",
"yanduan.polri.go.id",
"penerimaan.polri.go.id",
"rekrutmen.polri.go.id",
"lpse.polri.go.id",
"eppid.polri.go.id",
"ppid.polri.go.id",
"tv.polri.go.id",

// =========================
// KEJAKSAAN
// =========================
"kejaksaan.go.id",
"tilang.kejaksaan.go.id",
"e-tilang.kejaksaan.go.id",
"ppid.kejaksaan.go.id",
"lpse.kejaksaan.go.id",
"jdih.kejaksaan.go.id",
"cms.kejaksaan.go.id",
"eoffice.kejaksaan.go.id",
"simkari.kejaksaan.go.id",
"datun.kejaksaan.go.id",
"jamintel.kejaksaan.go.id",
"jamwas.kejaksaan.go.id",
"jamdatun.kejaksaan.go.id",
"jamintelbin.kejaksaan.go.id",
"puspenkum.kejaksaan.go.id",
"badiklat.kejaksaan.go.id",

// =========================
// BPJS KESEHATAN
// =========================
"bpjs-kesehatan.go.id",
"bpjskesehatan.go.id",
"mobilejkn.bpjs-kesehatan.go.id",
"pcare.bpjs-kesehatan.go.id",
"dsp.bpjs-kesehatan.go.id",
"edabu.bpjs-kesehatan.go.id",
"new-edabu.bpjs-kesehatan.go.id",
"antrean.bpjs-kesehatan.go.id",
"vclaim.bpjs-kesehatan.go.id",
"hfis.bpjs-kesehatan.go.id",
"aplikasi.bpjs-kesehatan.go.id",
"sso.bpjs-kesehatan.go.id",
"lpse.bpjs-kesehatan.go.id",
"ppid.bpjs-kesehatan.go.id",
"jdih.bpjs-kesehatan.go.id",

// =========================
// BPJS KETENAGAKERJAAN
// =========================
"bpjsketenagakerjaan.go.id",
"sso.bpjsketenagakerjaan.go.id",
"lapakasik.bpjsketenagakerjaan.go.id",
"ejmo.bpjsketenagakerjaan.go.id",
"antrian.bpjsketenagakerjaan.go.id",
"lapor.bpjsketenagakerjaan.go.id",
"lpse.bpjsketenagakerjaan.go.id",
"ppid.bpjsketenagakerjaan.go.id",
];