export const TRUSTED_GOVERNMENT_DOMAINS = [
  "indonesia.go.id",
  "lapor.go.id",
  "data.go.id",
  "domain.go.id",

  "presidenri.go.id",
  "setneg.go.id",

  "polkam.go.id",
  "ekon.go.id",
  "kemenkopmk.go.id",
  "maritim.go.id",

  "kemendagri.go.id",
  "kemlu.go.id",
  "kemenkeu.go.id",
  "kemenkum.go.id",
  "kemenag.go.id",
  "kemdikbud.go.id",
  "kemendikdasmen.go.id",
  "kemdiktisaintek.go.id",
  "kemenkes.go.id",
  "kemensos.go.id",
  "kemenkop.go.id",
  "kemenperin.go.id",
  "kemendag.go.id",
  "kementan.go.id",
  "kementrans.go.id",
  "esdm.go.id",
  "pu.go.id",
  "komdigi.go.id",
  "kemenparekraf.go.id",
  "kemenpora.go.id",
  "kemenpppa.go.id",
  "kemenpan.go.id",
  "bappenas.go.id",
  "atrbpn.go.id",
  "bkpm.go.id",

  "dpr.go.id",
  "dpd.go.id",
  "mpr.go.id",
  "bpk.go.id",
  "mahkamahagung.go.id",
  "mkri.id",
  "ky.go.id",

  "bnn.go.id",
  "bnpb.go.id",
  "bpip.go.id",
  "bssn.go.id",
  "bpkp.go.id",
  "bkn.go.id",
  "bawaslu.go.id",
  "kpu.go.id",
  "ombudsman.go.id",
  "bea-cukai.go.id",
  "pajak.go.id",
  "imigrasi.go.id",
  "kejaksaan.go.id",
  "polri.go.id",

  "cekbansos.kemensos.go.id",
  "sscasn.bkn.go.id",
  "djponline.pajak.go.id",
  "oss.go.id",
  "satu-sehat.go.id",
  "satusehat.kemkes.go.id",
  "lpse.go.id",
];